name: Node.js (deploy dev)
on:
  push:
    branches:
      - dev
    paths:
      - miaudocao_api/**
      
jobs:
  deploy:
    name: Deploy API to Heroku (dev)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Add remote origin
        run: git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
      - name: Deploy to Heroku
        run: git push --force heroku `git subtree split --prefix miaudocao_api HEAD`:main
